
server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root
  redis:
#    database: 1
#    password: imooc
#    sentinel:
#      master: mymaster
#      nodes: 121.89.195.81:26379,121.4.40.241:26379
    database: 1
    host: 121.89.195.81
    port: 6379
    password: imooc
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  configuration: # 日志配置，控制台输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
