#tomcat配置
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

#连接池配置
spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
#    password: root
    hikari:
      connection-timeout: 30000 #等待连接池分配连接的最大时常（毫秒），超过这个时常还没有可用的连接则会发生SQLException,默认：30秒
      minimum-idle: 5 #最小连接数
      maximum-pool-size: 20 #最大连接数
      auto-commit: true #自动提交
      idle-timeout: 600000 #连接超时的最大时长(毫秒)，超时则被释放(retired)
      pool-name: DataSourceHikariCP #连接池名字
      max-lifetime: 1800000 #连接的生命时长(毫秒)，超时而且没被使用则被释放
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000 #文件上传与下载大小限制
      max-request-size: 512000
#mybatis配置

mybatis:
  type-aliases-package: com.imooc.pojo #实体类的存放位置
  mapper-locations: classpath:mapper/*.xml

#  configuration: # 日志配置，控制台输出
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mapper:
  mappers: com.imooc.my.mapper.MyMapper #通用mapper的位置
  not-empty: false #在进行数据库操作的时候，判断表达式 是否为空
  #例如 username != null,是否追加 username != ''，尽量自己手写
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: mysql  #所支持的数据库
  support-methods-arguments: true



